// extension/ui/pages/txs/SendForm.tsx
import { useCallback, useMemo, useState } from "react"
import { FormProvider, useForm } from "react-hook-form"
import { mergeDeepRight } from "ramda"
import { Box, Button, Group, Input, Stack, Text, TextInput, UnstyledButton, useMantineTheme } from "@mantine/core"
import { useDisclosure, useElementSize } from "@mantine/hooks"
import { modals } from "@mantine/modals"
import { useQuery } from "@tanstack/react-query"
import {
  DEFAULT_SLIPPAGE_PERCENT,
  Tx,
  calcMinimum,
  getRest,
  required,
  toAmount,
  toQuantity,
  truncate,
  validateQuantityInput,
} from "@initia/utils"

import { defaultChain } from "../../../scripts/shared/chains"
import type { BaseAssetInfo } from "../../data/tokens"
import { useAddress, useLayers } from "../../background"
import styles from "../../styles/styles"
import Icon from "../../styles/Icon"
import Page from "../../components/Page"
import Num from "../../components/Num"
import FixedBottom from "../../components/FixedBottom"
import TokenLogo from "../../components/TokenLogo"

import useConfirm from "./helpers/useConfirm"
import SelectTargetChain from "./components/SelectTargetChain"
import SelectRecipient from "./components/SelectRecipient"
import SlippageTolerance from "./components/SlippageTolerance"
import FormError from "./components/FormError"
import Max from "./components/Max"
import Details from "./components/Details"

export interface SendValues {
  sourceChainId: string | number
  targetChainId: string | number
  recipientUsername?: string
  recipientAddress: string
  denom: string
  quantity: string
  memo: string
  slippage: string
}

interface Props extends BaseAssetInfo {
  denom: string
  chainId: string | number
  pairs?: Record<string, string>
}

const SendForm = ({ balance, symbol, decimals, denom, chainId, pairs, image }: Props) => {
  const { ref, width } = useElementSize()
  const theme = useMantineTheme()
  const defaultStyles = styles.TextInput(theme)

  const address = useAddress()
  const chain = defaultChain

  const layers = useLayers()
  const l1 = layers.find((layer) => layer.metadata?.is_l1)
  if (!l1) throw new Error("L1 not found")

  const confirm = useConfirm()

  /* form */
  const defaultValues = {
    denom,
    sourceChainId: chainId ?? chain.chainId,
    targetChainId: chainId ?? chain.chainId,
    recipientAddress: "",
    memo: "",
    quantity: "",
    slippage: String(DEFAULT_SLIPPAGE_PERCENT),
  }

  const [memoFixed, setMemoFixed] = useState(false)
  const form = useForm<SendValues>({ defaultValues })
  const { register, setValue, handleSubmit, watch, formState } = form
  const values = watch()
  const { sourceChainId, targetChainId, recipientAddress, memo, slippage = "" } = values

  const max = () => setValue("quantity", toQuantity(balance, decimals))

  const getDefinedLayer = useCallback(
    (chainId: string | number) => {
      return required(
        layers.find((layer) => layer.chain_id === chainId),
        "Layer not found",
      )
    },
    [layers],
  )

  const sourceLayer = useMemo(() => getDefinedLayer(sourceChainId), [getDefinedLayer, sourceChainId])
  const targetLayer = useMemo(() => getDefinedLayer(targetChainId), [getDefinedLayer, targetChainId])
  const amount = useMemo(() => toAmount(values.quantity, decimals), [values.quantity, decimals])

  const tx = useMemo(
    () => new Tx({ address, layer: sourceLayer, layer1: l1, modules: chain.modules, pairs }),
    [address, chain, l1, pairs, sourceLayer],
  )

  const send = useMemo(() => tx.send({ denom, targetLayer }), [denom, targetLayer, tx])

  /* simulation */
  const { data: simulated } = useQuery({
    queryKey: [getRest(l1), "Swap:Simulation", values],
    queryFn: async () => send.simulate({ amount }),
  })

  const minimum = useMemo(() => {
    if (!simulated) return
    return calcMinimum(simulated[0], slippage)
  }, [simulated, slippage])

  /* submit */
  const submit = handleSubmit(async () => {
    try {
      confirm({ messages: send.getMessages({ amount, recipientAddress, minimum }), memo }, chainId)
    } catch (error) {
      if (error instanceof Error) modals.open({ children: <Text c="danger">{error.message}</Text> })
    }
  })

  /* render */
  const showMemo = useMemo(() => {
    if (memoFixed) return false
    if (sourceChainId !== targetChainId) return false
    return true
  }, [memoFixed, sourceChainId, targetChainId])

  const [isMemoOpen, { toggle: toggleMemo }] = useDisclosure()
  const memoElement = !showMemo ? null : (
    <Box>
      <UnstyledButton onClick={toggleMemo}>
        <Group spacing={4}>
          <Icon.ChevronRight
            style={{ transition: "transform 150ms", transform: `rotate(${isMemoOpen ? "90deg" : "0"})` }}
          />
          <Text c="mono.2" fz={14} fw={600}>
            Memo (Optional)
          </Text>
        </Group>
      </UnstyledButton>

      {isMemoOpen && (
        <Box>
          <TextInput
            {...register("memo", {
              validate: {
                length: (value) => {
                  if (new Blob([value]).size <= 256) return
                  return "Memo must be less than 256 bytes"
                },
                brackets: (value) => {
                  if (value.includes("<") || value.includes(">")) return "Memo cannot include < or >"
                },
              },
            })}
            id="memo"
            error={formState.errors.memo?.message}
          />

          {!memo && (
            <FormError mt={8} info>
              Check if the above transaction requires a memo
            </FormError>
          )}
        </Box>
      )}
    </Box>
  )

  const quantityElement = (
    <Box>
      <Group position="apart">
        <Input.Label id="quantity" sx={defaultStyles.label}>
          Amount
        </Input.Label>
        <Max amount={balance} decimals={decimals} onClick={max} />
      </Group>

      <Box pos="relative">
        <Group spacing={4} pos="absolute" top={0} left={0} bottom={0} sx={{ zIndex: 1 }} px={20} ref={ref}>
          <TokenLogo image={image} size={20} />
          <Text>{truncate(symbol)}</Text>
        </Group>

        <TextInput
          {...register("quantity", { required: true, validate: validateQuantityInput({ balance, decimals }) })}
          id="quantity"
          placeholder="0"
          autoComplete="off"
          error={formState.errors.quantity?.message}
          styles={mergeDeepRight(defaultStyles, {
            input: { textAlign: "right" as const, paddingLeft: 2 * 20 + width },
          })}
        />
      </Box>
    </Box>
  )

  const details = !minimum
    ? undefined
    : [
        {
          title: "Minimum received",
          content: <Num amount={minimum} decimals={decimals} symbol={symbol} fixedByAmount />,
        },
      ]

  return (
    <Page title="Send">
      <FormProvider {...form}>
        <form onSubmit={submit}>
          <Stack spacing={20}>
            <SelectTargetChain />
            <SelectRecipient memoFixed={memoFixed} onMemoFixed={setMemoFixed} />
            {quantityElement}
            {memoElement}
            {details && <Details contents={details} />}
            {!!send.getSimulationParams({ amount }) && <SlippageTolerance />}
          </Stack>

          <FixedBottom>
            <Button type="submit">Next</Button>
          </FixedBottom>
        </form>
      </FormProvider>
    </Page>
  )
}

export default SendForm

// packages/wallet-widget/src/ui/pages/txs/SendForm.svelte
<script lang="ts">
import { BigNumber } from "bignumber.js"
import { createQuery } from "@tanstack/svelte-query"
import {
  DEFAULT_SLIPPAGE_PERCENT,
  Tx,
  calcMinimum,
  formatAmount,
  getRest,
  required,
  toAmount,
  truncate,
} from "@initia/utils"
import type { Chain } from "@initia/initia-registry-types"
import { getState, navigate } from "../../../lib/router/routing"
import { LayerQueries } from "../../../shared/queries"
import InitiaLayer, { getDecimals, getLogo } from "../../../layers/InitiaLayer"
import { modules } from "../../../stores/config"
import { address$ } from "../../../stores/state"
import { findLayer, getLayers } from "../../utils"
import Page from "../../components/Page.svelte"
import Stack from "../../components/Stack.svelte"
import Image from "../../components/Image.svelte"
import RecipientInput from "./components/RecipientInput.svelte"
import SlippageInput from "./components/SlippageInput.svelte"
import SelectWrapper from "../../components/SelectWrapper.svelte"

export let layer1: Chain
const address = $address$
const { denom, layer } = required(getState<{ denom: string; layer: Chain }>())
const { pairs, findAsset } = InitiaLayer.getInstance(layer.chain_id)

const layers = getLayers()
const asset = findAsset(denom)
const symbol = asset?.symbol
const logo = getLogo(asset)
const decimals = getDecimals(asset)

$: balanceQuery = createQuery(LayerQueries.getInstance(layer).balance(address, denom))
$: balance = $balanceQuery.data

/* form values */
let targetLayerChainId = layer.chain_id
let recipientAddress = ""
let value = ""
let memo = ""
let slippagePercent = DEFAULT_SLIPPAGE_PERCENT

/* tx */
$: amount = toAmount(value, decimals)
$: targetLayer = required(findLayer(targetLayerChainId))

const tx = new Tx({ address, layer, layer1, modules, pairs })
$: send = tx.send({ denom, targetLayer })

/* simulation */
$: simulationQuery = createQuery({
  queryKey: [getRest(layer1), "Swap:Simulation", { targetLayerChainId, amount }],
  queryFn: async () => send.simulate({ amount }),
})

$: simulated = $simulationQuery.data
$: minimum = simulated ? calcMinimum(simulated[0], String(slippagePercent)) : undefined

/* submit */
$: handleSubmit = () => {
  try {
    const messages = send.getMessages({ amount, recipientAddress, minimum })
    navigate("/confirm", { layer, txBodyValue: { messages, memo } })
  } catch (error) {
    window.alert(error)
  }
}

/* render */
$: disabled = !recipientAddress || !value || !balance || BigNumber(toAmount(value)).gt(balance)
</script>

<Page title="Send">
  <form on:submit|preventDefault={handleSubmit} id="form" class="scroll">
    <Stack gap={20}>
      <div>
        <label for="chain-id">Destination Network</label>

        <SelectWrapper iconRight={20}>
          <select class="input" bind:value={targetLayerChainId}>
            {#each layers as { chain_id, chain_name, pretty_name }}
              <option value={chain_id}>{pretty_name ?? chain_name}</option>
            {/each}
          </select>
        </SelectWrapper>
      </div>

      <RecipientInput bind:recipientAddress {layer1} />

      <div>
        <label for="value">Amount</label>

        <div class="wrapper">
          <div class="unit">
            <Image src={logo} alt={asset?.name + " logo"} width={20} height={20} />
            {asset?.symbol ?? truncate(denom)}
          </div>

          <button type="button" on:click={() => (value = formatAmount(balance, { decimals }))}>
            Available
            <span class="underline">{formatAmount(balance, { decimals })}</span>
          </button>
          <input type="text" id="value" placeholder="0" bind:value />
        </div>
      </div>

      <div>
        <label for="memo">Memo</label>
        <input type="text" id="memo" bind:value={memo} />
      </div>

      {#if minimum}
        <div class="item">
          <span class="title">Minimum received</span>
          <div class="content">{formatAmount(minimum, { decimals })} {symbol}</div>
        </div>
      {/if}
    </Stack>
  </form>

  <footer class="footer">
    {#if send.getSimulationParams({ amount })}
      <SlippageInput bind:value={slippagePercent} />
    {/if}
    <button type="submit" form="form" class="submit" {disabled}>Submit</button>
  </footer>
</Page>

<style>
input#value {
  font-size: 24px;
  height: 100px;
  text-align: right;
  padding-top: 30px;
}

.wrapper {
  position: relative;
}

.wrapper .unit {
  position: absolute;
  top: 20px;
  left: 20px;

  display: flex;
  align-items: center;
  gap: 4px;

  color: var(--gray-0);
  font-size: 16px;
  font-weight: 700;
}

.wrapper button {
  position: absolute;
  top: 24px;
  right: 20px;

  display: flex;
  gap: 6px;

  font-size: 12px;
  font-weight: 700;
  color: var(--gray-5);
}

.wrapper button .underline {
  color: var(--gray-1);
}

.item {
  display: flex;
  justify-content: space-between;

  color: var(--gray-1);
  font-size: 12px;
  font-weight: 600;
}

.item .title {
  color: var(--gray-3);
}

.footer {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.submit {
  flex: none;
}
</style>
