// extension/ui/pages/home/ManageLayers.tsx
import { useDisclosure } from "@mantine/hooks"
import { Drawer, Group, Stack, Text, UnstyledButton } from "@mantine/core"
import { useQuery } from "@tanstack/react-query"
import { createHTTPClient } from "@initia/utils"
import type { Chain } from "@initia/initia-registry-types"
import { defaultChain } from "../../../scripts/shared/chains"
import { useLayers } from "../../background"
import Page from "../../components/Page"
import Icon from "../../styles/Icon"
import AddCustomLayer from "./AddCustomLayer"
import ManageLayerItem from "./ManageLayerItem"

export type CompactChain = Pick<
  Chain,
  "chain_id" | "chain_name" | "pretty_name" | "description" | "logo_URIs" | "website"
>

const ManageLayers = () => {
  const layers = useLayers()
  const [opened, { open, close }] = useDisclosure()

  const chain = defaultChain
  const { omnitia } = chain
  const { data: allLayers = [] } = useQuery({
    queryKey: [omnitia, "layers"],
    queryFn: async () => createHTTPClient(omnitia).get<CompactChain[]>("/v1/registry/chains/compact"),
  })

  const notAddedLayers = allLayers.filter((layer) => !layers.some((l) => l.chain_id === layer.chain_id))

  return (
    <Page title="Manage my Minitias">
      <Stack spacing={28}>
        <Stack spacing={8}>
          <Text tt="uppercase">Shown</Text>

          {layers.map((layer) => (
            <ManageLayerItem layer={layer} key={layer.chain_id} />
          ))}
        </Stack>

        <Stack spacing={8}>
          <Group position="apart">
            <Text tt="uppercase">{notAddedLayers.length === 0 ? "" : "Hidden"}</Text>

            <UnstyledButton c="mono.4" onClick={open}>
              <Group spacing={2}>
                <Icon.Plus width={10} height={10} />
                <Text fz={12} fw={600}>
                  Add a custom Minitia
                </Text>
              </Group>
            </UnstyledButton>
          </Group>

          {notAddedLayers.map((layer) => (
            <ManageLayerItem layer={layer} key={layer.chain_id} />
          ))}
        </Stack>
      </Stack>

      <Drawer opened={opened} onClose={close}>
        <AddCustomLayer onClose={close} />
      </Drawer>
    </Page>
  )
}

export default ManageLayers

// packages/wallet-widget/src/ui/pages/home/ManageLayers.svelte
<script lang="ts">
import { createQuery } from "@tanstack/svelte-query"
import { createHTTPClient } from "@initia/utils"
import type { Chain } from "@initia/initia-registry-types"
import { omnitiaURL } from "../../../stores/config"
import LayerManager from "../../../layers/LayerManager"
import Page from "../../components/Page.svelte"
import Stack from "../../components/Stack.svelte"
import ManageLayersItem from "./ManageLayersItem.svelte"

const allLayersQuery = createQuery({
  queryKey: ["allLayers"],
  queryFn: async () => {
    const omniClient = createHTTPClient(omnitiaURL)
    return omniClient.get<
      Pick<Chain, "chain_id" | "chain_name" | "pretty_name" | "description" | "logo_URIs" | "website">[]
    >("/v1/registry/chains/compact")
  },
})

$: ({ data: allLayers = [] } = $allLayersQuery)

const layersManagerInstance = LayerManager.getInstance()
const layers$ = layersManagerInstance.layers$
$: addedLayers = $layers$
$: notAddedLayers = allLayers.filter(
  (layer) => !addedLayers.some((addedLayer) => addedLayer.chain_id === layer.chain_id),
)
</script>

<Page title="Manage my Minitias">
  <section class="scroll">
    <Stack gap={8}>
      <h2>Shown</h2>

      {#each addedLayers as layer (layer.chain_id)}
        <ManageLayersItem {layer} isAdded />
      {/each}
    </Stack>

    <div class="divider" />

    {#if notAddedLayers.length > 0}
      <Stack gap={8}>
        <h2>Hidden</h2>
        {#each notAddedLayers as layer (layer.chain_id)}
          <ManageLayersItem {layer} />
        {/each}
      </Stack>
    {/if}
  </section>
</Page>

<style>
.divider {
  margin: 28px 0;
}

h2 {
  color: var(--gray-1);
  font-size: 12px;
  font-weight: 700;
}
</style>
