// packages/wallet-widget/src/ui/pages/txs/components/Price.svelte
<script lang="ts">
import BigNumber from "bignumber.js"
import { formatNumber } from "@initia/utils"

export let price: string | number
export let offerSymbol: string
export let askSymbol: string

let showOfferToAsk = BigNumber(price).gt(1)

$: toggle = () => {
  showOfferToAsk = !showOfferToAsk
}

$: offerToAsk = `1 ${offerSymbol} = ${formatNumber(price)} ${askSymbol}`
$: askToOffer = `1 ${askSymbol} = ${formatNumber(BigNumber(1).div(price).toString())} ${offerSymbol}`
</script>

<button type="button" on:click={toggle}>
  {#if showOfferToAsk}
    {offerToAsk}
  {:else}
    {askToOffer}
  {/if}
</button>

// extension/ui/pages/txs/components/Price.tsx
import BigNumber from "bignumber.js"
import Num from "../../../components/Num"

interface Props {
  price: string | number
  offerSymbol: string
  askSymbol: string
}

const Price = ({ offerSymbol, askSymbol, ...props }: Props) => {
  if (!props.price) return null

  const price = BigNumber(props.price)

  return price.gt(1) ? (
    <>
      <Num amount={1} symbol={offerSymbol} decimals={0} /> ={" "}
      <Num amount={price.toString()} symbol={askSymbol} decimals={0} fixedByAmount />
    </>
  ) : (
    <>
      <Num amount={1} symbol={askSymbol} decimals={0} /> ={" "}
      <Num amount={BigNumber(1).div(price).toString()} symbol={offerSymbol} decimals={0} fixedByAmount />
    </>
  )
}

export default Price
